### ISSUE TITLE
flake8==3.0.0 broke this hook

### ISSUE THREAD

**Issue by chriskuehl** [asottile/cheetah_lint#14]
From their docs, they don't have a public API anymore: http://flake8.pycqa.org/en/latest/user/python-api.html

They provide a "legacy" API that is supposed to mimic the old API, but the behavior has changed significantly.

If we can't fix this quickly, we should pin 2.x so that people won't get broken hooks (cc @virgytam).

I tried to fix this myself but didn't get too far. Here's my attempt (tests: 16 failed, 101 passed):

``` patch
diff --git a/.gitignore b/.gitignore
index 2626934..79ee9ff 100644
--- a/.gitignore
+++ b/.gitignore
@@ -11,3 +11,4 @@
 /venv*
 coverage-html
 dist
+/.cache
diff --git a/cheetah_lint/flake.py b/cheetah_lint/flake.py
index 6e204d8..241b9fc 100644
--- a/cheetah_lint/flake.py
+++ b/cheetah_lint/flake.py
@@ -8,10 +8,10 @@ import re
 import sys
 import tokenize

-import pycodestyle
+from flake8.api.legacy import formatter
 from Cheetah.compile import compile_source
 from Cheetah.legacy_compiler import LegacyCompiler
-from flake8.engine import get_style_guide
+from flake8.api.legacy import get_style_guide

 from cheetah_lint import five
 from cheetah_lint.util import read_file
@@ -83,9 +83,9 @@ def to_py(src):
     )


-class DataCollectingReporter(pycodestyle.BaseReport):
-    """A Reporter for pycodestyle/flake8 which simply collects data instead of
-    spewing to stdout.
+class DataCollectingReporter(formatter.BaseFormatter):
+    """A Reporter for flake8 which simply collects data instead of spewing to
+    stdout.
     """

     def __init__(self, *args, **kwargs):
@@ -264,10 +264,11 @@ def normalize_line_numbers(data, py_lines, cheetah_lines):
 def check_flake8(py_lines):
     # Apologies, flake8 doesn't quite make this elegant / easy
     checker = get_style_guide(select=SELECTED_ERRORS)
-    reporter = checker.init_report(DataCollectingReporter)
+    checker._application.formatter = None
+    checker.init_report(DataCollectingReporter)
     checker.input_file('<compiled cheetah>', py_lines)
     return filter_known_unused_assignments(filter_known_unused_imports(
-        reporter.data,
+        checker._application.formatter.data,
     ))


diff --git a/setup.py b/setup.py
index b5907e7..b48d6f3 100644
--- a/setup.py
+++ b/setup.py
@@ -22,7 +22,7 @@ setup(
     install_requires=[
         'aspy.refactor_imports>=0.2.1',
         'cached-property',
-        'flake8>=2.6.0',
+        'flake8>=3.0.0',
         'refactorlib[cheetah]>=0.13.0,<=0.13.999',
         'yelp-cheetah>=0.17.0,<=0.17.999',
     ],
```

**Comment by asottile** [comment]
grr, ok I'll put <=2.999 for now, and we can fix later

**Comment by asottile** [comment]
Limited to <3 in 8f8df4247cfc8da4cd3e665c6575bc9398da8488

**Comment by asottile** [comment]
Blocked by https://gitlab.com/pycqa/flake8/issues/200

**Comment by asottile** [comment]
I could also subprocess or something, that seems icky :S

**Comment by jayvdb** [comment]
What is the benefit of using `flake8`?
Do you need flake8 plugins?
I am guessing that you dont benefit from flake8 processing multiple files concurrently...?

You are already using `pycodestyle.BaseReport` , and controlling the error's reported.
You could use `pyflakes` and `pycodestyle` directly, and expect those APIs to not disappear on you.

**Comment by asottile** [comment]
flake8 conveniently normalizes and combines those and allows for exclusion as well as plugin extension.  Well, at least it did before 3.x

**Comment by jayvdb** [comment]
The ignore functionality of flake8 v2 is actually a very thin wrapper over the pycodestyle ignore functionality.

And it is one line of code to integrate pyflakes into pycodestyle, if you dont mind loosing the `Fxxx` codes that flake8 adds.

I see you are running some tokenize-based checks separately; if you used pycodestyle directly, you can avoid the second tokenize by asking pycodestyle to run your checker.

Agreed flake8 is a bit more convenient, and it is necessary if you want flake8 plugins.

**Comment by sigmavirus24** [comment]
@jayvdb "The ignore functionality of flake8 v2" is **not** a "thin wrapper over the pycodestyle ignore functionality". pycodestyle did all of that. Flake8 only handled it in so much as off-by-default plugins were considered.

**Comment by jayvdb** [comment]
Ergo, it is a thin wrapper.

**Comment by sigmavirus24** [comment]
That implies we changed the behaviour, which we did not. We extended the default ignore list if a plugin was off-by-default. There was no wrapping, just proxying.

**Comment by asottile** [comment]
Since flake8 doesn't provide an api for linting text in process any more, we'll have to write out a temporary file and lint that.

CC @dan98765
